services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insurehub_api
    ports:
      - "8002:8001"
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
    environment:
      - EMBED_MODEL=BAAI/bge-base-en-v1.5
      - VLLM_HOST=http://123.253.124.14:7000
      - VLLM_MODEL=Qwen/Qwen2.5-7B-Instruct-AWQ
    volumes:
      - insurehub_data:/root/.insurehub
      - insurehub_tmp:/root/.insurehub_tmp
      - hf_cache:/root/.cache/huggingface
      - whisper_cache:/root/.cache/whisper
    restart: unless-stopped

volumes:
  insurehub_data:
  insurehub_tmp:
  hf_cache:
  whisper_cache:
